---
- name: Ensure directory
  file:
    path: '{{ docker_config_path }}'
    state: directory
    owner: root
    group: root

- name: Ensure configuration
  template:
    src: '{{ docker_config_template_file }}'
    dest: '{{ docker_config_file }}'
    owner: root
    group: root
    mode: '0644'
  notify:
  - reload systemd daemon
  - restart docker
