---
- name: Creates directory
  file:
    path: '{{ docker_config_path }}'
    state: directory
    owner: root
    group: root
  when: ansible_distribution_major_version|int == 7

- name: Ensure configuration RHEL7
  template:
    src: '{{ docker_dropin_template_file }}'
    dest: '{{ docker_config_file }}'
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution_major_version|int == 7
  notify:
    - Systemd daemon-reload
    - Restart Docker

- name: Ensure configuration
  template:
    src: '{{ docker_dropin_template_file }}'
    dest: '{{ docker_config_file }}'
    owner: root
    group: root
    mode: '0644'
  when: ansible_distribution_major_version|int == 6
  notify:
    - Restart Docker
