---
- name: Ensure repository
  template:
    src: '{{ docker_repository_template_file }}'
    dest: /etc/yum.repos.d/docker.repo
    owner: root
    group: root
    mode: '0644'

- name: Ensure package
  yum:
    name: '{{ docker_package_name }}'
    state: '{{ docker_package_state }}'
    enablerepo: '{{ docker_packages_repo | default(omit) }}'
