---
- include_vars: '{{ ansible_distribution }}{{ansible_distribution_major_version }}.{{ansible_architecture }}.yml'

- name: Install docker
  sudo: true
  yum:
    name: '{{ item }}'
    state: '{{ docker_package_state }}'
    enablerepo: '{{ docker_packages_repo | default(omit) }}'
  with_items: docker_packages

- name: Ensure that service is running and configured to start on system boot
  sudo: true
  service:
    name: '{{ docker_service_name }}'
    state: '{{ docker_service_state }}'
    enabled: '{{ docker_service_enabled }}'