---
- include_vars: '{{ item }}'
  with_first_found:
  - '{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_distribution }}.yml'
  - '{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml'
  - '{{ ansible_os_family }}.yml'

- include: install.yml
  tags: docker_install

- include: config.yml
  tags: docker_config

- include: service.yml
  tags: docker_service

- meta: flush_handlers
  when: '{{ docker_flush_handlers }}'
