---
- name: reload systemd daemon
  command: /bin/systemctl daemon-reload
  when: ansible_distribution_major_version|int == 7

- name: restart docker
  service:
    name: '{{ docker_service_name }}'
    state: restarted

- name: stop docker
  service:
    name: '{{ docker_service_name }}'
    state: stopped
